version: '3.7'
services:
  maac:
  # MAAC Environment (build an appropriate image in ../../images/)
    image: mdde/env/maac:latest
    depends_on:
      - registry
    networks:
      back:
        aliases:
          - maac
    volumes:
      - mdde_shared:/mdde/shared
    environment:
      - REG_HOST=registry
      - REG_PORT=8942
